lib/eurovision2019_web/router.ex
defmodule Eurovision2019Web.Router do
  use Eurovision2019Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Eurovision2019Web do
    pipe_through :browser

    get "/", EditionController, :vote
    resources "/registrations", UserController, only: [:create, :new]
    get "/sign-in", SessionController, :new
    post "/sign-in", SessionController, :create
    delete "/sign-out", SessionController, :delete
    resources "/accounts", UserController
    resources "/participants", ParticipantController

    resources "/editions", EditionController,
      only: [:new, :index, :create, :edit, :update, :delete]

    get "/editions/:id/close", EditionController, :close
    get "/editions/results", EditionController, :results
    get "/editions/vote", EditionController, :vote
  end

  # Other scopes may use custom stacks.
  # scope "/api", Eurovision2019Web do
  #   pipe_through :api
  # end
end

lib/eurovision2019_web/views/layout_view.ex
defmodule Eurovision2019Web.LayoutView do
  use Eurovision2019Web, :view
end

lib/eurovision2019_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Eurofreaks</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <div class="header">
          <div class="logo">
            <img src="/images/eurovision.svg">
          </div>
          <div class="links">
            <div class="menu">
              <%= link "Votaciones", to: Routes.edition_path(@conn, :vote) %>
              |
              <%= link "Resultados", to: Routes.edition_path(@conn, :results) %>
            </div>
            <div class="session">
              <%= if signed_in?(@conn) do %>
                <%= link "Salir", to: Routes.session_path(@conn, :delete), method: :delete %>
              <% else %>
                <%= link "Entrar", to: Routes.session_path(@conn, :new) %>
              <% end %>
            </div>
          </div>
        </div>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>